//! Testing Utilities Module
//!
//! This module contains useful structures for writing tests against this library.

use rdkafka::mocking::MockCluster;
use std::{collections::HashSet, sync::LazyLock, thread::spawn};
use tokio::{
    sync::{
        RwLock,
        mpsc::{self, Sender},
        oneshot,
    },
    task::spawn_blocking,
};

/// Global instance of [`MockKafka`] to be used by all test cases.
/// Utilizes [`LazyLock`] to only instantiate it once it has been referenced for the first time.
/// All subsequent references will see the same instance.
static MOCK_CLUSTER: LazyLock<MockKafka> = LazyLock::new(MockKafka::new);

/// The function to drive the [`MockCluster`] process.
/// Reports the host path to the [`MockKafka`] that kicks this off, then listens for requests to create new topics.
fn run_cluster(host_sender: oneshot::Sender<String>, mut topic_receiver: mpsc::Receiver<String>) {
    let mock_cluster = MockCluster::new(3).unwrap();
    host_sender
        .send(mock_cluster.bootstrap_servers())
        .expect("Could not send the host to the MockKafka instance");

    // `blocking_recv` will return `None` when all senders are dropped (i.e., when tests are over).
    while let Some(topic) = topic_receiver.blocking_recv() {
        let _ = mock_cluster.create_topic(&topic, 3, 1);
    }
}

/// A struct to manage the [`MockCluster`] thread across the test runs.
/// Maintains a list of the known topics to short-circuit the process of sending a new topic String across the threads.
struct MockKafka {
    host: String,
    known_topics: RwLock<HashSet<String>>,
    topic_sender: Sender<String>,
}
impl MockKafka {
    fn new() -> Self {
        let (topic_sender, topic_receiver) = mpsc::channel::<String>(1);
        let (host_sender, host_receiver) = oneshot::channel();

        spawn(move || {
            run_cluster(host_sender, topic_receiver);
        });

        let host = host_receiver
            .blocking_recv()
            .expect("Failed to acquire host path for the mock cluster");

        MockKafka {
            host,
            known_topics: RwLock::default(),
            topic_sender,
        }
    }

    fn host(&self) -> String {
        self.host.clone()
    }

    fn is_alive(&self) -> bool {
        true
    }

    async fn create_topic(&self, topic: String) {
        let has_topic = self.known_topics.read().await.contains(&topic);
        if !has_topic {
            let mut write_lock = self.known_topics.write().await;
            let is_missing_topic_after_acquiring_write_lock = !write_lock.contains(&topic);
            if is_missing_topic_after_acquiring_write_lock {
                self.topic_sender
                    .send(topic.clone())
                    .await
                    .expect("Failed to add topic to cluster");
                write_lock.insert(topic);
            }
        }
    }
}

/// A set of values for running tests against an instance of [`MockCluster`].
///
/// ## WARNING
/// To conserve resources, this structure references a global instance of [`MockCluster`].
/// If topic names are reused between test cases, messages from one test case may become visible to another.
/// There is no guarantee of consistency on this, so do not build tests in anticipation of specific data from
/// another test being present.
///
/// Corollary: build tests on independent topics or design them to be agnostic
/// about preexisting data.
pub struct Harness;
impl Harness {
    /// Generates an instance of [`Harness`] with a reference to a global [`MockCluster`] that has been
    /// prepopulated with the specified topics.
    pub async fn with_topics(topics: Vec<String>) -> Self {
        assert!(
            spawn_blocking(|| MOCK_CLUSTER.is_alive())
                .await
                .expect("Failed to start mock cluster")
        );
        for topic in topics {
            MOCK_CLUSTER.create_topic(topic).await;
        }
        Harness
    }

    /// Returns the comma-delimited list of addresses generated by the [`MockCluster`].
    pub fn host(&self) -> String {
        MOCK_CLUSTER.host()
    }
}
