name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@e0c90cb1aa154991276dbdd6a4eccfd676b5208b
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      references-internal-git-repo: true
      static-dependencies: 'libcurl4-openssl-dev librdkafka-dev libsasl2-dev'
