name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@bbd8c72f44a8589bc3375f5d75f73f9e0b5f7ab4
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      references-internal-git-repo: true
